name: Build Workflow

on:
  push:
    branches: dev

jobs:

  check_project_compilation_and_tests:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set TERM variable
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: Launch make re
        run: make re
        timeout-minutes: 3

      - name: Check executable
        run: |
          if [ -f DEFINE_NAME ]; then
            echo "Executable does exists"
          else
            echo "Executable does not exist"
            exit 1
          fi
        timeout-minutes: 2

      - name: Launch tests
        run: make tests_script
        timeout-minutes: 3

